"use client";

import { PieChart, Clock, ListChecks, CheckCircle2, XCircle, AlertCircle, ChevronDown, ChevronUp } from "lucide-react";
import { useState } from "react";
import { cn } from "@/shared/lib/utils";

const TEST_RESULTS = [
  { id: 1, name: "Verify Homepage Load and Welcome Text", status: "passed", time: "2.1s", error: null },
  { id: 2, name: "Verify Web Demo Navigation", status: "passed", time: "6.1s", error: null },
  { id: 3, name: "Verify Localization Switcher", status: "passed", time: "2.2s", error: null },
  { id: 4, name: "Negative Test: Verify 404 on Invalid Route", status: "passed", time: "1.5s", error: null },
  { id: 5, name: "Edge Test: Verify Mobile Navigation Menu", status: "passed", time: "3.4s", error: null },
];

export function TestReportDashboard() {
  const [expandedTest, setExpandedTest] = useState<number | null>(4); // Default expand the failed one

  const totalTests = TEST_RESULTS.length;
  const passed = TEST_RESULTS.filter(t => t.status === "passed").length;
  const failed = TEST_RESULTS.filter(t => t.status === "failed").length;
  const skipped = TEST_RESULTS.filter(t => t.status === "skipped").length;
  
  const passRate = Math.round((passed / totalTests) * 100);

  return (
    <div className="w-full rounded-xl overflow-hidden border border-white/10 shadow-2xl bg-white/5 backdrop-blur-md">
      {/* Header */}
      <div className="bg-black/20 px-6 py-4 border-b border-white/10 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <PieChart className="text-accent-blue" />
            Automation Test Report
          </h3>
          <p className="text-sm text-text-muted mt-1">Generated by Playwright Reporter</p>
        </div>
        <div className="flex gap-4">
          <div className="glass px-4 py-2 rounded-lg text-center">
            <div className="text-2xl font-bold text-white">{totalTests}</div>
            <div className="text-xs text-text-muted">Total Tests</div>
          </div>
          <div className="glass px-4 py-2 rounded-lg text-center">
            <div className="text-2xl font-bold text-green-400">{passRate}%</div>
            <div className="text-xs text-text-muted">Pass Rate</div>
          </div>
          <div className="glass px-4 py-2 rounded-lg text-center">
            <div className="text-2xl font-bold text-accent-cyan flex items-center justify-center gap-1">
              <Clock size={16} />
              22.6s
            </div>
            <div className="text-xs text-text-muted">Duration</div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="p-6">
        <div className="flex flex-wrap gap-3 mb-6">
          <div className="bg-green-500/10 border border-green-500/20 text-green-400 px-3 py-1.5 rounded-full text-sm font-medium flex items-center gap-2">
            <CheckCircle2 size={16} /> {passed} Passed
          </div>
          <div className="bg-red-500/10 border border-red-500/20 text-red-400 px-3 py-1.5 rounded-full text-sm font-medium flex items-center gap-2">
            <XCircle size={16} /> {failed} Failed
          </div>
          <div className="bg-gray-500/10 border border-gray-500/20 text-gray-400 px-3 py-1.5 rounded-full text-sm font-medium flex items-center gap-2">
            <AlertCircle size={16} /> {skipped} Skipped
          </div>
        </div>

        <div className="space-y-2">
          {TEST_RESULTS.map((test) => (
            <div key={test.id} className="border border-white/5 rounded-lg overflow-hidden bg-black/20 hover:bg-black/40 transition-colors">
              <button 
                className="w-full px-4 py-3 flex items-center justify-between text-left"
                onClick={() => test.status === 'failed' && setExpandedTest(expandedTest === test.id ? null : test.id)}
                disabled={test.status !== 'failed'}
              >
                <div className="flex items-center gap-3">
                  {test.status === "passed" && <CheckCircle2 className="text-green-400" size={18} />}
                  {test.status === "failed" && <XCircle className="text-red-400" size={18} />}
                  {test.status === "skipped" && <AlertCircle className="text-gray-400" size={18} />}
                  <span className={cn(
                    "font-medium text-sm md:text-base",
                    test.status === "failed" ? "text-red-200" : "text-gray-200"
                  )}>
                    {test.name}
                  </span>
                </div>
                <div className="flex items-center gap-4">
                  <span className="text-sm text-gray-500 font-mono">{test.time}</span>
                  {test.status === "failed" && (
                    expandedTest === test.id ? <ChevronUp size={18} className="text-gray-400" /> : <ChevronDown size={18} className="text-gray-400" />
                  )}
                </div>
              </button>
              
              {expandedTest === test.id && test.error && (
                <div className="px-4 py-3 bg-red-950/30 border-t border-red-900/30 font-mono text-xs md:text-sm text-red-300 whitespace-pre-wrap overflow-x-auto">
                  {test.error}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
